apiVersion: v1
kind: Service
metadata:
  name: svc-prometheus-grafana
  namespace: monitoring
spec:
  ports:
    - name: prometheus-grafana
      port: 80
      nodePort: 30090
  selector:
    app: svc-prometheus-grafana
  type: NodePort