apiVersion: v1
kind: Service
metadata:
  name: prometheus-grafana
  namespace: monitoring
spec:
  ports:
    - name: prometheus-grafana
      port: 3000
      targetPort: 3000
      nodePort: 30090
  selector:
    app.kubernetes.io/name: grafana
  type: NodePort
